
import type { Question, Topic, Difficulty } from '@/types/quiz';

// Mock question database - in a real app, this would be generated by AI
const questionBank: Partial<Record<Topic, Partial<Record<Difficulty, Question[]>>>> = {
  Python: {
    Beginner: [
      {
        id: '1',
        question: 'What is the correct way to create a list in Python?',
        options: ['list = []', 'list = ()', 'list = {}', 'list = ""'],
        correctAnswer: 'list = []',
        explanation: 'Lists in Python are created using square brackets []. Parentheses () create tuples, curly braces {} create dictionaries or sets, and quotes "" create strings.',
        topic: 'Python',
        difficulty: 'Beginner'
      },
      {
        id: '2',
        question: 'Which of the following is used to add an element to the end of a list?',
        options: ['add()', 'append()', 'insert()', 'extend()'],
        correctAnswer: 'append()',
        explanation: 'The append() method adds a single element to the end of a list. insert() adds at a specific position, extend() adds multiple elements, and add() is used for sets.',
        topic: 'Python',
        difficulty: 'Beginner'
      },
      {
        id: '3',
        question: 'What does the len() function return?',
        options: ['The last element', 'The first element', 'The number of elements', 'The sum of elements'],
        correctAnswer: 'The number of elements',
        explanation: 'The len() function returns the number of items (length) in an object like a string, list, tuple, or dictionary.',
        topic: 'Python',
        difficulty: 'Beginner'
      }
    ],
    Intermediate: [
      {
        id: '4',
        question: 'What is a Python decorator?',
        options: ['A design pattern', 'A function that modifies another function', 'A data structure', 'A built-in module'],
        correctAnswer: 'A function that modifies another function',
        explanation: 'A decorator is a function that takes another function as an argument and extends or modifies its behavior without explicitly modifying the function itself.',
        topic: 'Python',
        difficulty: 'Intermediate'
      },
      {
        id: '5',
        question: 'Which method is used to handle exceptions in Python?',
        options: ['catch-finally', 'try-except', 'handle-error', 'exception-catch'],
        correctAnswer: 'try-except',
        explanation: 'Python uses try-except blocks to handle exceptions. Code that might raise an exception goes in the try block, and exception handling code goes in the except block.',
        topic: 'Python',
        difficulty: 'Intermediate'
      }
    ]
  },
  JavaScript: {
    Beginner: [
      {
        id: '6',
        question: 'How do you declare a variable in JavaScript?',
        options: ['var x;', 'variable x;', 'v x;', 'declare x;'],
        correctAnswer: 'var x;',
        explanation: 'Variables in JavaScript can be declared using var, let, or const keywords. var is the traditional way, though let and const are preferred in modern JavaScript.',
        topic: 'JavaScript',
        difficulty: 'Beginner'
      },
      {
        id: '7',
        question: 'What does the === operator do in JavaScript?',
        options: ['Assignment', 'Loose equality', 'Strict equality', 'Not equal'],
        correctAnswer: 'Strict equality',
        explanation: 'The === operator performs strict equality comparison, checking both value and type. It does not perform type coercion like the == operator.',
        topic: 'JavaScript',
        difficulty: 'Beginner'
      }
    ]
  },
  Git: {
    Beginner: [
      {
        id: '8',
        question: 'What command is used to initialize a new Git repository?',
        options: ['git start', 'git init', 'git create', 'git new'],
        correctAnswer: 'git init',
        explanation: 'The "git init" command creates a new Git repository in the current directory, setting up the necessary .git folder and initial structure.',
        topic: 'Git',
        difficulty: 'Beginner'
      },
      {
        id: '9',
        question: 'Which command shows the current status of your Git repository?',
        options: ['git show', 'git status', 'git info', 'git state'],
        correctAnswer: 'git status',
        explanation: 'The "git status" command displays the state of the working directory and staging area, showing which files are modified, staged, or untracked.',
        topic: 'Git',
        difficulty: 'Beginner'
      }
    ]
  }
};

export const generateQuestions = async (topic: Topic, difficulty: Difficulty): Promise<Question[]> => {
  // Simulate API delay
  await new Promise(resolve => setTimeout(resolve, 1500));
  
  const topicQuestions = questionBank[topic];
  const difficultyQuestions = topicQuestions?.[difficulty] || [];
  
  // If we have questions for this topic/difficulty, return them
  if (difficultyQuestions.length > 0) {
    // Shuffle and return 3-5 questions
    const shuffled = [...difficultyQuestions].sort(() => Math.random() - 0.5);
    return shuffled.slice(0, Math.min(5, shuffled.length));
  }
  
  // Fallback: generate some generic questions
  return generateFallbackQuestions(topic, difficulty);
};

const generateFallbackQuestions = (topic: Topic, difficulty: Difficulty): Question[] => {
  const fallbackQuestions: Question[] = [
    {
      id: `fallback-${topic}-${difficulty}-1`,
      question: `What is a key concept in ${topic} that ${difficulty.toLowerCase()} developers should know?`,
      options: [
        'Basic syntax and structure',
        'Advanced optimization techniques',
        'Enterprise architecture patterns',
        'Legacy system integration'
      ],
      correctAnswer: difficulty === 'Beginner' ? 'Basic syntax and structure' : 
                    difficulty === 'Intermediate' ? 'Advanced optimization techniques' : 
                    'Enterprise architecture patterns',
      explanation: `Understanding ${difficulty.toLowerCase()} concepts in ${topic} is essential for building a strong foundation in this technology.`,
      topic,
      difficulty
    },
    {
      id: `fallback-${topic}-${difficulty}-2`,
      question: `Which practice is most important when working with ${topic}?`,
      options: [
        'Following best practices',
        'Writing clean code',
        'Testing thoroughly',
        'All of the above'
      ],
      correctAnswer: 'All of the above',
      explanation: `All these practices are crucial when working with ${topic} to ensure maintainable and reliable code.`,
      topic,
      difficulty
    },
    {
      id: `fallback-${topic}-${difficulty}-3`,
      question: `What is a common challenge when learning ${topic}?`,
      options: [
        'Understanding the syntax',
        'Managing complexity',
        'Keeping up with updates',
        'Finding good resources'
      ],
      correctAnswer: difficulty === 'Beginner' ? 'Understanding the syntax' : 'Managing complexity',
      explanation: `${difficulty} level learners often face this challenge when working with ${topic}.`,
      topic,
      difficulty
    }
  ];
  
  return fallbackQuestions;
};
